package com.gymflow.service;

import com.gymflow.model.ClassSession;
import com.gymflow.exception.DataAccessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

public class ClassScheduleServiceImplTest {

    private ClassScheduleService classScheduleService;

    @BeforeEach
    public void setUp() {
        // Initialize the service (which initializes the DAO)
        classScheduleService = new ClassScheduleServiceImpl();
    }

    @Test
    public void testCreateClassSession_Success() {
        long trainerId = 1;
        String title = "Yoga Flow";
        LocalDateTime scheduleTime = LocalDateTime.now().plusDays(1); // Tomorrow
        int capacity = 20;

        Optional<ClassSession> result = classScheduleService.createClassSession(trainerId, title, scheduleTime, capacity);

        assertTrue(result.isPresent(), "Class session should be created");
        assertNotNull(result.get().getId(), "ID should be generated");
        assertTrue(result.get().getId() > 0, "ID should be greater than 0");
        assertEquals(title, result.get().getTitle());
    }

    @Test
    public void testGetClassSessionById_Existing() {
        // 1. SETUP: Create a session first to ensure it exists!
        long trainerId = 1;
        String title = "Test HIIT";
        LocalDateTime scheduleTime = LocalDateTime.now().plusDays(2);

        Optional<ClassSession> created = classScheduleService.createClassSession(trainerId, title, scheduleTime, 15);
        assertTrue(created.isPresent(), "Setup failed: Could not create class session");

        // 2. GET ID: Get the real ID generated by the database
        long generatedId = created.get().getId();

        // 3. EXECUTE: Now try to find it using the REAL ID
        Optional<ClassSession> found = classScheduleService.getClassSessionById(generatedId);

        // 4. ASSERT
        assertTrue(found.isPresent(), "Should find the class session we just created");
        assertEquals(title, found.get().getTitle());
    }

    @Test
    public void testGetClassSessionById_NonExisting() {
        // Use a massive ID that likely doesn't exist
        long nonExistentId = 999999L;
        Optional<ClassSession> found = classScheduleService.getClassSessionById(nonExistentId);
        assertFalse(found.isPresent(), "Should not find a session with ID 999999");
    }

    @Test
    public void testGetUpcomingClassSessions() {
        // Setup: Create a future class
        classScheduleService.createClassSession(1, "Future Class", LocalDateTime.now().plusDays(5), 10);

        List<ClassSession> upcoming = classScheduleService.getUpcomingClassSessions();

        assertNotNull(upcoming);
        assertFalse(upcoming.isEmpty(), "Should have at least one upcoming class");
    }
}