package com.gymflow.service;

import com.gymflow.dao.ClassSessionDao;
import com.gymflow.dao.ClassSessionDaoImpl;
import com.gymflow.model.ClassSession;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Implementation of ClassScheduleService for class session business logic.
 */
public class ClassScheduleServiceImpl implements ClassScheduleService {
    private final ClassSessionDao classSessionDao;

    public ClassScheduleServiceImpl() {
        this.classSessionDao = new ClassSessionDaoImpl();
    }

    @Override
    public Optional<ClassSession> createClassSession(long trainerId, String title, 
                                                    LocalDateTime scheduleTimestamp, int capacity) {
        // Validation
        if (title == null || title.trim().isEmpty()) {
            System.err.println("Class session title cannot be empty");
            return Optional.empty();
        }

        if (trainerId <= 0) {
            System.err.println("Invalid trainer ID");
            return Optional.empty();
        }

        if (scheduleTimestamp == null) {
            System.err.println("Schedule timestamp is required");
            return Optional.empty();
        }

        if (scheduleTimestamp.isBefore(LocalDateTime.now())) {
            System.err.println("Cannot schedule class in the past");
            return Optional.empty();
        }

        if (capacity <= 0) {
            System.err.println("Capacity must be greater than 0");
            return Optional.empty();
        }

        // Create class session object (id will be generated by database)
        ClassSession classSession = new ClassSession(0, trainerId, title.trim(), 
                                                    scheduleTimestamp, capacity);

        // Save to database
        Optional<ClassSession> created = classSessionDao.create(classSession);
        
        if (created.isPresent()) {
            System.out.println("Class session created successfully: " + title);
        } else {
            System.err.println("Failed to create class session: " + title);
        }

        return created;
    }

    @Override
    public List<ClassSession> getClassSessionsByTrainer(long trainerId) {
        if (trainerId <= 0) {
            System.err.println("Invalid trainer ID");
            return List.of();
        }

        return classSessionDao.findByTrainerId(trainerId);
    }

    @Override
    public List<ClassSession> getUpcomingClassSessions() {
        return classSessionDao.findUpcoming();
    }

    @Override
    public Optional<ClassSession> getClassSessionById(long sessionId) {
        if (sessionId <= 0) {
            return Optional.empty();
        }

        return classSessionDao.findById(sessionId);
    }

    @Override
    public boolean updateClassSession(long sessionId, String title, LocalDateTime scheduleTimestamp, int capacity) {
        Optional<ClassSession> existingOpt = classSessionDao.findById(sessionId);
        
        if (existingOpt.isEmpty()) {
            System.err.println("Class session not found: " + sessionId);
            return false;
        }

        ClassSession existing = existingOpt.get();

        // Update only provided fields
        if (title != null && !title.trim().isEmpty()) {
            existing.setTitle(title.trim());
        }
        if (scheduleTimestamp != null) {
            if (scheduleTimestamp.isBefore(LocalDateTime.now())) {
                System.err.println("Cannot schedule class in the past");
                return false;
            }
            existing.setScheduleTimestamp(scheduleTimestamp);
        }
        if (capacity > 0) {
            existing.setCapacity(capacity);
        }

        boolean success = classSessionDao.update(existing);
        
        if (success) {
            System.out.println("Class session updated successfully: " + sessionId);
        } else {
            System.err.println("Failed to update class session: " + sessionId);
        }

        return success;
    }

    @Override
    public boolean deleteClassSession(long sessionId) {
        if (sessionId <= 0) {
            return false;
        }

        boolean success = classSessionDao.delete(sessionId);
        
        if (success) {
            System.out.println("Class session deleted successfully: " + sessionId);
        } else {
            System.err.println("Failed to delete class session: " + sessionId);
        }

        return success;
    }
}

