package com.gymflow.service;

import com.gymflow.dao.ClassSessionDao;
import com.gymflow.dao.ClassSessionDaoImpl;
import com.gymflow.model.ClassSession;
import com.gymflow.exception.DataAccessException;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Implementation of ClassScheduleService for class session business logic.
 */
public class ClassScheduleServiceImpl implements ClassScheduleService {
    private final ClassSessionDao classSessionDao;

    public ClassScheduleServiceImpl() {
        this.classSessionDao = new ClassSessionDaoImpl();
    }

    @Override
    public Optional<ClassSession> createClassSession(long trainerId, String title, 
                                                    LocalDateTime scheduleTimestamp, int capacity) throws DataAccessException {
        // Validation
        if (title == null || title.trim().isEmpty()) {
            throw new IllegalArgumentException("Class session title cannot be empty");
        }
        if (trainerId <= 0) {
            throw new IllegalArgumentException("Invalid trainer ID");
        }
        if (scheduleTimestamp == null) {
            throw new IllegalArgumentException("Schedule timestamp is required");
        }
        if (scheduleTimestamp.isBefore(LocalDateTime.now())) {
            throw new IllegalArgumentException("Cannot schedule class in the past");
        }
        if (capacity <= 0) {
            throw new IllegalArgumentException("Capacity must be greater than 0");
        }
        // Create class session object (id will be generated by database)
        ClassSession classSession = new ClassSession(0, trainerId, title.trim(), 
                                                    scheduleTimestamp, capacity);
        // Save to database
        try {
            Optional<ClassSession> created = classSessionDao.create(classSession);
            if (created.isPresent()) {
                return created;
            } else {
                throw new DataAccessException("Failed to create class session: " + title);
            }
        } catch (Exception e) {
            throw new DataAccessException("Exception creating class session: " + title, e);
        }
    }

    @Override
    public List<ClassSession> getClassSessionsByTrainer(long trainerId) throws DataAccessException {
        if (trainerId <= 0) {
            throw new IllegalArgumentException("Invalid trainer ID");
        }
        try {
            return classSessionDao.findByTrainerId(trainerId);
        } catch (Exception e) {
            throw new DataAccessException("Failed to get class sessions for trainer: " + trainerId, e);
        }
    }

    @Override
    public List<ClassSession> getUpcomingClassSessions() throws DataAccessException {
        try {
            return classSessionDao.findUpcoming();
        } catch (Exception e) {
            throw new DataAccessException("Failed to get upcoming class sessions", e);
        }
    }

    @Override
    public Optional<ClassSession> getClassSessionById(long sessionId) throws DataAccessException {
        if (sessionId <= 0) {
            throw new IllegalArgumentException("Invalid session ID");
        }
        try {
            return classSessionDao.findById(sessionId);
        } catch (Exception e) {
            throw new DataAccessException("Failed to get class session by id: " + sessionId, e);
        }
    }

    @Override
    public boolean updateClassSession(long sessionId, String title, LocalDateTime scheduleTimestamp, int capacity) throws DataAccessException {
        try {
            Optional<ClassSession> existingOpt = classSessionDao.findById(sessionId);
            if (existingOpt.isEmpty()) {
                throw new DataAccessException("Class session not found: " + sessionId);
            }
            ClassSession existing = existingOpt.get();
            // Update only provided fields
            if (title != null && !title.trim().isEmpty()) {
                existing.setTitle(title.trim());
            }
            if (scheduleTimestamp != null) {
                if (scheduleTimestamp.isBefore(LocalDateTime.now())) {
                    throw new IllegalArgumentException("Cannot schedule class in the past");
                }
                existing.setScheduleTimestamp(scheduleTimestamp);
            }
            if (capacity > 0) {
                existing.setCapacity(capacity);
            }
            boolean success = classSessionDao.update(existing);
            if (!success) {
                throw new DataAccessException("Failed to update class session: " + sessionId);
            }
            return true;
        } catch (Exception e) {
            throw new DataAccessException("Error updating class session: " + sessionId, e);
        }
    }

    @Override
    public boolean deleteClassSession(long sessionId) throws DataAccessException {
        if (sessionId <= 0) {
            throw new IllegalArgumentException("Invalid session ID");
        }
        try {
            boolean success = classSessionDao.delete(sessionId);
            if (!success) {
                throw new DataAccessException("Failed to delete class session: " + sessionId);
            }
            return true;
        } catch (Exception e) {
            throw new DataAccessException("Error deleting class session: " + sessionId, e);
        }
    }

    @Override
    public boolean assignWorkoutPlanToClass(long sessionId, Long workoutPlanId) throws DataAccessException {
        if (sessionId <= 0) {
            throw new IllegalArgumentException("Invalid session ID");
        }
        try {
            Optional<ClassSession> existingOpt = classSessionDao.findById(sessionId);
            if (existingOpt.isEmpty()) {
                throw new DataAccessException("Class session not found: " + sessionId);
            }
            ClassSession existing = existingOpt.get();
            existing.setWorkoutPlanId(workoutPlanId);
            boolean success = classSessionDao.update(existing);
            if (!success) {
                throw new DataAccessException("Failed to assign workout plan to class session: " + sessionId);
            }
            return true;
        } catch (Exception e) {
            throw new DataAccessException("Error assigning workout plan to class session: " + sessionId, e);
        }
    }
}

