package com.gymflow.service;

import com.gymflow.dao.EquipmentDao;
import com.gymflow.dao.EquipmentDaoImpl;
import com.gymflow.model.Equipment;
import com.gymflow.model.EquipmentStatus;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

/**
 * Implementation of EquipmentService for equipment management business logic.
 */
public class EquipmentServiceImpl implements EquipmentService {
    private final EquipmentDao equipmentDao;

    public EquipmentServiceImpl() {
        this.equipmentDao = new EquipmentDaoImpl();
    }

    @Override
    public Optional<Equipment> createEquipment(String name, EquipmentStatus status, LocalDate lastServiceDate) {
        // Validation
        if (name == null || name.trim().isEmpty()) {
            System.err.println("Equipment name cannot be empty");
            return Optional.empty();
        }

        EquipmentStatus equipmentStatus = status != null ? status : EquipmentStatus.AVAILABLE;

        // Create equipment object (id will be generated by database)
        Equipment equipment = new Equipment(0, name.trim(), equipmentStatus, lastServiceDate);

        // Save to database
        Optional<Equipment> created = equipmentDao.create(equipment);
        
        if (created.isPresent()) {
            System.out.println("Equipment created successfully: " + name);
        } else {
            System.err.println("Failed to create equipment: " + name);
        }

        return created;
    }

    @Override
    public List<Equipment> getAllEquipment() {
        return equipmentDao.findAll();
    }

    @Override
    public List<Equipment> getEquipmentByStatus(EquipmentStatus status) {
        if (status == null) {
            return List.of();
        }

        return equipmentDao.findByStatus(status);
    }

    @Override
    public Optional<Equipment> getEquipmentById(long equipmentId) {
        if (equipmentId <= 0) {
            return Optional.empty();
        }

        return equipmentDao.findById(equipmentId);
    }

    @Override
    public boolean updateEquipment(long equipmentId, String name, EquipmentStatus status, LocalDate lastServiceDate) {
        Optional<Equipment> existingOpt = equipmentDao.findById(equipmentId);
        
        if (existingOpt.isEmpty()) {
            System.err.println("Equipment not found: " + equipmentId);
            return false;
        }

        Equipment existing = existingOpt.get();

        // Update only provided fields
        if (name != null && !name.trim().isEmpty()) {
            existing.setName(name.trim());
        }
        if (status != null) {
            existing.setStatus(status);
        }
        if (lastServiceDate != null) {
            existing.setLastServiceDate(lastServiceDate);
        }

        boolean success = equipmentDao.update(existing);
        
        if (success) {
            System.out.println("Equipment updated successfully: " + equipmentId);
        } else {
            System.err.println("Failed to update equipment: " + equipmentId);
        }

        return success;
    }

    @Override
    public boolean updateEquipmentStatus(long equipmentId, EquipmentStatus status) {
        if (equipmentId <= 0 || status == null) {
            return false;
        }

        boolean success = equipmentDao.updateStatus(equipmentId, status);
        
        if (success) {
            System.out.println("Equipment status updated successfully: " + equipmentId + " -> " + status);
        } else {
            System.err.println("Failed to update equipment status: " + equipmentId);
        }

        return success;
    }

    @Override
    public boolean markEquipmentForService(long equipmentId) {
        return updateEquipmentStatus(equipmentId, EquipmentStatus.MAINTENANCE);
    }
}

