package com.gymflow.service;

import com.gymflow.dao.WorkoutPlanDao;
import com.gymflow.dao.WorkoutPlanDaoImpl;
import com.gymflow.model.WorkoutPlan;
import com.gymflow.exception.DataAccessException;

import java.util.List;
import java.util.Optional;

/**
 * Implementation of WorkoutService for workout plan business logic.
 */

public class WorkoutServiceImpl implements WorkoutService {
    private final WorkoutPlanDao workoutPlanDao;

    public WorkoutServiceImpl() {
        this.workoutPlanDao = new WorkoutPlanDaoImpl();
    }

    @Override
    public Optional<WorkoutPlan> createWorkoutPlan(long memberId, long trainerId, String title,
                                                   String description, String difficulty) throws DataAccessException {
        // Validation
        if (title == null || title.trim().isEmpty()) {
            throw new IllegalArgumentException("Workout plan title cannot be empty");
        }

        if (memberId <= 0 || trainerId <= 0) {
            throw new IllegalArgumentException("Invalid member or trainer ID");
        }

        // Normalize difficulty
        String normalizedDifficulty = difficulty != null ? difficulty.trim() : "Beginner";

        // Create workout plan object (id will be generated by database)
        WorkoutPlan workoutPlan = new WorkoutPlan(0, memberId, trainerId, title.trim(),
                description != null ? description.trim() : null,
                normalizedDifficulty, null);

        // Save to database
        Optional<WorkoutPlan> created = workoutPlanDao.create(workoutPlan);
        if (created.isPresent()) {
            return created;
        } else {
            throw new DataAccessException("Failed to create workout plan: " + title);
        }
    }

    @Override
    public Optional<WorkoutPlan> createWorkoutPlan(long memberId, long trainerId, String title,
                                                   String description, String difficulty, String muscleGroup,
                                                   String workoutType, Integer durationMinutes, String equipmentNeeded,
                                                   Integer targetSets, Integer targetReps, Integer restSeconds) throws DataAccessException {
        // Validation
        if (title == null || title.trim().isEmpty()) {
            throw new IllegalArgumentException("Workout plan title cannot be empty");
        }

        if (memberId <= 0 || trainerId <= 0) {
            throw new IllegalArgumentException("Invalid member or trainer ID");
        }

        // Normalize difficulty
        String normalizedDifficulty = difficulty != null ? difficulty.trim() : "Beginner";

        // Create workout plan object with all fields (id will be generated by database)
        WorkoutPlan workoutPlan = new WorkoutPlan(0, memberId, trainerId, title.trim(),
                description != null ? description.trim() : null,
                normalizedDifficulty,
                muscleGroup != null && !muscleGroup.trim().isEmpty() ? muscleGroup.trim() : null,
                workoutType != null && !workoutType.trim().isEmpty() ? workoutType.trim() : null,
                durationMinutes,
                equipmentNeeded != null && !equipmentNeeded.trim().isEmpty() ? equipmentNeeded.trim() : null,
                targetSets,
                targetReps,
                restSeconds,
                null);

        // Save to database
        Optional<WorkoutPlan> created = workoutPlanDao.create(workoutPlan);
        if (created.isPresent()) {
            return created;
        } else {
            throw new DataAccessException("Failed to create workout plan: " + title);
        }
    }

    @Override
    public List<WorkoutPlan> getWorkoutPlansForMember(long memberId) throws DataAccessException {
        if (memberId <= 0) {
            throw new IllegalArgumentException("Invalid member ID");
        }
        try {
            return workoutPlanDao.findByMemberId(memberId);
        } catch (Exception e) {
            throw new DataAccessException("Failed to get workout plans for member: " + memberId, e);
        }
    }

    @Override
    public List<WorkoutPlan> getWorkoutPlansByTrainer(long trainerId) throws DataAccessException {
        if (trainerId <= 0) {
            throw new IllegalArgumentException("Invalid trainer ID");
        }
        try {
            return workoutPlanDao.findByTrainerId(trainerId);
        } catch (Exception e) {
            throw new DataAccessException("Failed to get workout plans for trainer: " + trainerId, e);
        }
    }

    @Override
    public Optional<WorkoutPlan> getWorkoutPlanById(long planId) throws DataAccessException {
        if (planId <= 0) {
            throw new IllegalArgumentException("Invalid plan ID");
        }
        try {
            return workoutPlanDao.findById(planId);
        } catch (Exception e) {
            throw new DataAccessException("Failed to get workout plan by id: " + planId, e);
        }
    }

    @Override
    public boolean updateWorkoutPlan(long planId, String title, String description, String difficulty) throws DataAccessException {
        try {
            Optional<WorkoutPlan> existingOpt = workoutPlanDao.findById(planId);
            if (existingOpt.isEmpty()) {
                throw new DataAccessException("Workout plan not found: " + planId);
            }
            WorkoutPlan existing = existingOpt.get();
            // Update only provided fields
            if (title != null && !title.trim().isEmpty()) {
                existing.setTitle(title.trim());
            }
            if (description != null) {
                existing.setDescription(description.trim());
            }
            if (difficulty != null && !difficulty.trim().isEmpty()) {
                existing.setDifficulty(difficulty.trim());
            }
            boolean success = workoutPlanDao.update(existing);
            if (!success) {
                throw new DataAccessException("Failed to update workout plan: " + planId);
            }
            return true;
        } catch (Exception e) {
            throw new DataAccessException("Error updating workout plan: " + planId, e);
        }
    }

    @Override
    public boolean deleteWorkoutPlan(long planId) throws DataAccessException {
        if (planId <= 0) {
            throw new IllegalArgumentException("Invalid plan ID");
        }
        try {
            boolean success = workoutPlanDao.delete(planId);
            if (!success) {
                throw new DataAccessException("Failed to delete workout plan: " + planId);
            }
            return true;
        } catch (Exception e) {
            throw new DataAccessException("Error deleting workout plan: " + planId, e);
        }
    }
}