package com.gymflow.service;

import com.gymflow.dao.WorkoutPlanDao;
import com.gymflow.dao.WorkoutPlanDaoImpl;
import com.gymflow.model.WorkoutPlan;

import java.util.List;
import java.util.Optional;

/**
 * Implementation of WorkoutService for workout plan business logic.
 */
public class WorkoutServiceImpl implements WorkoutService {
    private final WorkoutPlanDao workoutPlanDao;

    public WorkoutServiceImpl() {
        this.workoutPlanDao = new WorkoutPlanDaoImpl();
    }

    @Override
    public Optional<WorkoutPlan> createWorkoutPlan(long memberId, long trainerId, String title, 
                                                   String description, String difficulty) {
        // Validation
        if (title == null || title.trim().isEmpty()) {
            System.err.println("Workout plan title cannot be empty");
            return Optional.empty();
        }

        if (memberId <= 0 || trainerId <= 0) {
            System.err.println("Invalid member or trainer ID");
            return Optional.empty();
        }

        // Normalize difficulty
        String normalizedDifficulty = difficulty != null ? difficulty.trim() : "Beginner";

        // Create workout plan object (id will be generated by database)
        WorkoutPlan workoutPlan = new WorkoutPlan(0, memberId, trainerId, title.trim(), 
                                                  description != null ? description.trim() : null,
                                                  normalizedDifficulty, null);

        // Save to database
        Optional<WorkoutPlan> created = workoutPlanDao.create(workoutPlan);
        
        if (created.isPresent()) {
            System.out.println("Workout plan created successfully: " + title);
        } else {
            System.err.println("Failed to create workout plan: " + title);
        }

        return created;
    }

    @Override
    public List<WorkoutPlan> getWorkoutPlansForMember(long memberId) {
        if (memberId <= 0) {
            System.err.println("Invalid member ID");
            return List.of();
        }

        return workoutPlanDao.findByMemberId(memberId);
    }

    @Override
    public List<WorkoutPlan> getWorkoutPlansByTrainer(long trainerId) {
        if (trainerId <= 0) {
            System.err.println("Invalid trainer ID");
            return List.of();
        }

        return workoutPlanDao.findByTrainerId(trainerId);
    }

    @Override
    public Optional<WorkoutPlan> getWorkoutPlanById(long planId) {
        if (planId <= 0) {
            return Optional.empty();
        }

        return workoutPlanDao.findById(planId);
    }

    @Override
    public boolean updateWorkoutPlan(long planId, String title, String description, String difficulty) {
        Optional<WorkoutPlan> existingOpt = workoutPlanDao.findById(planId);
        
        if (existingOpt.isEmpty()) {
            System.err.println("Workout plan not found: " + planId);
            return false;
        }

        WorkoutPlan existing = existingOpt.get();

        // Update only provided fields
        if (title != null && !title.trim().isEmpty()) {
            existing.setTitle(title.trim());
        }
        if (description != null) {
            existing.setDescription(description.trim());
        }
        if (difficulty != null && !difficulty.trim().isEmpty()) {
            existing.setDifficulty(difficulty.trim());
        }

        boolean success = workoutPlanDao.update(existing);
        
        if (success) {
            System.out.println("Workout plan updated successfully: " + planId);
        } else {
            System.err.println("Failed to update workout plan: " + planId);
        }

        return success;
    }

    @Override
    public boolean deleteWorkoutPlan(long planId) {
        if (planId <= 0) {
            return false;
        }

        boolean success = workoutPlanDao.delete(planId);
        
        if (success) {
            System.out.println("Workout plan deleted successfully: " + planId);
        } else {
            System.err.println("Failed to delete workout plan: " + planId);
        }

        return success;
    }
}

